Update RunTests.yml

diff --git a/.github/workflows/RunTests.yml b/.github/workflows/RunTests.yml
--- a/.github/workflows/RunTests.yml
+++ b/.github/workflows/RunTests.yml
@@ -54,9 +54,17 @@ jobs:
       - name: 'Generate Apex Test List'
         id: testlist
         run: |
-          sf apextests list --format sf > testlist.txt
-          echo "TESTS=$(cat testlist.txt)" >> GITHUB_ENV
-          
+        run: |
+          sf apextests list --json > testlist.json
+          echo "TESTS=$(cat testlist.json)" >> GITHUB_ENV
+
+      - name: 'Verify Test List'
+        run: |
+          if [ ! -s testlist.json ]; then
+            echo "No tests found or generation failed."
+            exit 1
+          fi
+
       - name: 'Email Tests'
         uses: dawidd6/action-send-mail@v3
         with:
@@ -64,10 +72,10 @@ jobs:
           server_port: 587
           username: ${{ secrets.SMTP_USERNAME }}
           password: ${{ secrets.SMTP_PASSWORD }}
-          subject: "APEX Tests"
+          subject: "Apex Test Classes List"
           to: ${{ github.repository_owner }}
           from: "github-actions@example.com"
           body: |
-            Please find attached the Apex tests.
-          attachments: testlist.txt  
+            Attached is the generated list of Apex test classes in JSON format.
+          attachments: testlist.json
           
