Update RunTests.yml

diff --git a/.github/workflows/RunTests.yml b/.github/workflows/RunTests.yml
--- a/.github/workflows/RunTests.yml
+++ b/.github/workflows/RunTests.yml
@@ -53,9 +53,9 @@ jobs:
 
       - name: 'Generate Apex Test List'
         id: testlist
+        continue-on-error: true
         run: |
-          sf apextests list --json > testlist.json
-          echo "TESTS=$(cat testlist.json)" >> GITHUB_ENV
+          sf apextests list --json > testlist.json || echo '{"error": "Failed to get list"}' > testlist.json
 
       - name: 'Verify Test List'
         run: |
